### ISSUE TITLE
Events::Event

### ISSUE THREAD

**Issue by cuBeUrg** [ragempcommunity/ragemp-types#29]
#### Missing Type

https://wiki.rage.mp/index.php?title=Events::Event

#### Proof that this type exists.

https://wiki.rage.mp/index.php?title=Events::Event

#### Additional Information/Comments

😘

**Comment by leonardssh** [comment]
Already exists and it seems to work perfectly. 👍

https://github.com/ragempcommunity/ragemp-types/blob/a1638c5866b3fcd5af75f4ee25f969b077e0fa56/packages/server/index.d.ts#L1865

https://github.com/ragempcommunity/ragemp-types/blob/a1638c5866b3fcd5af75f4ee25f969b077e0fa56/packages/server/index.d.ts#L1331-L1340

**Comment by cuBeUrg** [comment]
> Already exists and it seems to work perfectly. 👍
> 
> https://github.com/ragempcommunity/ragemp-types/blob/a1638c5866b3fcd5af75f4ee25f969b077e0fa56/packages/server/index.d.ts#L1865
> 
> https://github.com/ragempcommunity/ragemp-types/blob/a1638c5866b3fcd5af75f4ee25f969b077e0fa56/packages/server/index.d.ts#L1331-L1340

Nu are trebui sa fie si pe client?
