### ISSUE TITLE
hasPendingRPC and cancelPendingRPC  not exist

### ISSUE THREAD

**Issue by PartizanChg** [ragempcommunity/ragemp-types#60]
hasPendingRPC -> hasPendingProc
cancelPendingRPC -> cancelPendingProc

**Comment by shr0x** [comment]
Fixed [b1e2d55](https://github.com/ragempcommunity/ragemp-types/commit/b1e2d55eb90c01a7f9c1caecb0651fd1796d1c98) &  [65984bc](https://github.com/ragempcommunity/ragemp-types/commit/65984bc201118f542b0650fa3e9473431fced4f2)
